Updated confh Updated confh with support for editing init.vim modules

diff --git a/.local/bin/confh b/.local/bin/confh
--- a/.local/bin/confh
+++ b/.local/bin/confh
@@ -8,6 +8,9 @@
 
 CUR_VER=$( sed '4q;d' ~/.local/bin/confh | cut -d ' ' -f3)
 
+RED=$(tput setaf 196)
+RESET=$(tput sgr0)
+
 function _check_ver {
 	if [ "$1" -gt "$4" ] || [ "$2" -gt "$5" ] || [ "$3" -gt "$6" ]; then
 		echo "New version $1.$2.$3 found online ( Old: $4.$5.$6 )."
@@ -22,7 +25,8 @@ function _bashrc {
 	case $1 in
 		"-e"|"--edit")
 			echo "Opening ~/.bashrc in $EDITOR"
-			$EDITOR ~/.bashrc || { echo "Variable EDITOR is not set, using nano"; nano ~/.bashrc; }
+			[ -z "$EDITOR" ] && { echo "${RED}Variable EDITOR is not set, using nano$RESET" > /dev/stderr; sleep 1; nano ~/.bashrc; return 0; }
+			$EDITOR ~/.bashrc
 			return 0
 			;;
 		"-s"|"--resource")
@@ -33,9 +37,9 @@ function _bashrc {
 		"-u"|"--update")
 			local REPO="https://raw.githubusercontent.com/BreadyX/dotfiles/master/.bashrc"
 			LOCAL_VERSION=( $(sed '3q;d' ~/.bashrc | cut -d ' ' -f3 | sed 's/\./ /g') )
-			( cd /tmp || { echo "/tmp is not available, please fix" > /dev/stderr ; return 1; }
+			( cd /tmp || { echo "${RED}/tmp is not available, please fix${RESET}" > /dev/stderr ; return 1; }
 			echo "Checking for updates..."
-			wget -V &> /dev/null || { echo "wget is not installed. Please install wget and then continue" > /dev/stderr ; }
+			wget -V &> /dev/null || { echo "${RED}wget is not installed. Please install wget and then continue$RESET" > /dev/stderr ; }
 			wget -O .bashrc $REPO &> /dev/null
 			REMOTE_VERSION=( $(sed '3q;d' ./.bashrc | cut -d ' ' -f3 | sed 's/\./ /g') )
 			if _check_ver "${REMOTE_VERSION[@]}" "${LOCAL_VERSION[@]}"; then
@@ -59,7 +63,8 @@ function _bash_profile {
 	case $1 in
 		"-e"|"--edit")
 			echo "Opening ~/.bash_profile in $EDITOR"
-			$EDITOR ~/.bash_profile || { echo "Variable EDITOR is not set, using nano"; nano ~/.bash_profile; }
+			[ -z "$EDITOR" ] && { echo "${RED}Variable EDITOR is not set, using nano$RESET" > /dev/stderr; sleep 1; nano ~/.bash_profile; return 0; }
+			$EDITOR ~/.bash_profile
 			return 0
 			;;
 		"-s"|"--resource")
@@ -70,9 +75,9 @@ function _bash_profile {
 		"-u"|"--update")
 			local REPO="https://raw.githubusercontent.com/BreadyX/dotfiles/master/.bash_profile"
 			LOCAL_VERSION=( $(sed '3q;d' ~/.bash_profile | cut -d ' ' -f3 | sed 's/\./ /g') )
-			( cd /tmp || { echo "/tmp is not available, please fix" > /dev/stderr ; return 1; }
+			( cd /tmp || { echo "${RED}/tmp is not available, please fix$RESET" > /dev/stderr ; return 1; }
 			echo "Checking for updates..."
-			wget -V &> /dev/null || { echo "wget is not installed. Please install wget and then continue" > /dev/stderr ; }
+			wget -V &> /dev/null || { echo "${RED}wget is not installed. Please install wget and then continue$RESET" > /dev/stderr ; }
 			wget -O .bash_profile $REPO &> /dev/null
 			REMOTE_VERSION=( $(sed '3q;d' ./.bash_profile | cut -d ' ' -f3 | sed 's/\./ /g') )
 			if _check_ver "${REMOTE_VERSION[@]}" "${LOCAL_VERSION[@]}"; then
@@ -96,13 +101,43 @@ function _init_vim {
     echo "$(tput setaf 196)NOT YET FULLY IMPLEMENTED, DON'T EXPECT CORRECT BEHAVIOUR$(tput sgr0)"
 	case $1 in
 		"-e"|"--edit")
-			echo "Opening init.vim in $EDITOR"
-			$EDITOR ~/.config/nvim/init.vim || { echo "Variable EDITOR is not set, using nano"; nano ~/.config/nvim/init.vim; }
-			return 0
+			echo "Do you want to open one of init.vim's modules (default yes)? [Y/N]"
+			read -r INPUT;
+			if [ "${INPUT,,}" == "n" ]; then
+				echo "Opening init.vim in $EDITOR"
+				[ -z "$EDITOR" ] && { echo "${RED}Variable EDITOR is not set, using nano$RESET" > /dev/stderr; sleep 1; nano ~/.config/nvim/init.vim; }
+				$EDITOR ~/.config/nvim/init.vim
+				return 0
+			else
+				echo "Which module do you want to open (default init.vim)"
+				MODULES=( $(dir ~/.config/nvim/*.vim) )
+				for (( i=0; i<${#MODULES[@]}; i++ )); do echo "[$i] $(basename "${MODULES[$i]}")"; done
+				read -r INPUT
+				case $INPUT in
+					*[!0-9]*)
+						echo "${RED}Selection '$INPUT' is invalid$RESET" > /dev/stderr; return 1
+						;;
+					'')
+						[ -z "$EDITOR" ] && { echo "${RED}Variable EDITOR is not set, using nano$RESET" > /dev/stderr; sleep 1; nano ~/.config/nvim/init.vim; return 0; }
+						$EDITOR ~/.config/nvim/init.vim
+						return 0
+						;;
+					*)
+						[ -z "${MODULES[$INPUT]}" ] && { echo "${RED}Selection '$INPUT' is invalid$RESET" > /dev/stderr; return 1; }
+						[ -z "$EDITOR" ] && { echo "${RED}Variable EDITOR is not set, using nano$RESET" > /dev/stderr; sleep 1; nano "${MODULES[$INPUT]}"; return 0; }
+						$EDITOR "${MODULES[$INPUT]}"
+						return 0
+						;;
+				esac
+			fi
 			;;
 		"-u"|"--upgrade")
-			CONFIRM=0
-			if [ "$2" == "--all" ] || [ "$3" == "--all" ]; then CONFIRM=1; fi
+			if [ "$3" == "--all" ] || [ "$4" == "--all" ]; then
+				echo "Upgrading all vim config files"
+				( echo "starting procedure"; )
+			else
+				echo "Choose which files to upgrade:"
+			fi
 			;;
 		*)
 			echo "Unknown option $1, please see conf --help for info about usage"
